name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          REMOTE_DEPLOY_PATH: ${{ secrets.REMOTE_DEPLOY_PATH }}
        run: |
          echo "=====1====="
          echo "$SSH_PRIVATE_KEY" > private_key
          echo $SSH_PRIVATE_KEY
          echo "=====2====="
          chmod 600 private_key
          echo "=====3====="
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST -t
          echo "=====4====="
          sudo su root
          echo "=====5====="
          cd $REMOTE_DEPLOY_PATH
          echo "=====6====="
          git pull
          echo "=====7====="
          npm run build
          echo "=====8====="
          systemctl restart nginx
          echo "=====9====="
